import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div style={{ display: "flex", minHeight: "100vh" }}>
          <nav
            style={{
              width: 220,
              background: "#fafafa",
              borderRight: "1px solid #eee",
              padding: 24,
            }}
          >
            <h3 style={{ fontWeight: 700, fontSize: 18, marginBottom: 16 }}>
              Components
            </h3>
            <ul style={{ listStyle: "none", padding: 0, margin: 0 }}>
              <li>
                <Link href="/accordion">Accordion</Link>
              </li>
              <li>
                <Link href="/button">Button</Link>
              </li>
              <li>
                <Link href="/card">Card</Link>
              </li>
              <li>
                <Link href="/input">Input</Link>
              </li>
              <li>
                <Link href="/label">Label</Link>
              </li>
              <li>
                <Link href="/tooltip">Tooltip</Link>
              </li>
            </ul>
          </nav>
          <main style={{ flex: 1, padding: 32 }}>{children}</main>
        </div>
      </body>
    </html>
  );
}
