import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

const components = [
  { name: "Button", slug: "button" },
  { name: "Input", slug: "input" },
  // Add more components here
];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div style={{ display: "flex", minHeight: "100vh" }}>
          <aside
            style={{ width: 200, padding: 24, borderRight: "1px solid #eee" }}
          >
            <h3>Components</h3>
            <ul>
              {components.map((comp) => (
                <li key={comp.slug}>
                  <Link href={`/${comp.slug}`}>{comp.name}</Link>
                </li>
              ))}
            </ul>
          </aside>
          <main style={{ flex: 1, padding: 24 }}>{children}</main>
        </div>
      </body>
    </html>
  );
}
