// @ts-nocheck -- skip type checking
import * as docs_9 from "../content/docs/components/tooltip.mdx?collection=docs&hash=1751702889991"
import * as docs_8 from "../content/docs/components/label.mdx?collection=docs&hash=1751702889991"
import * as docs_7 from "../content/docs/components/input.mdx?collection=docs&hash=1751702889991"
import * as docs_6 from "../content/docs/components/card.mdx?collection=docs&hash=1751702889991"
import * as docs_5 from "../content/docs/components/button.mdx?collection=docs&hash=1751702889991"
import * as docs_4 from "../content/docs/components/accordion.mdx?collection=docs&hash=1751702889991"
import * as docs_3 from "../content/docs/installation.mdx?collection=docs&hash=1751702889991"
import * as docs_2 from "../content/docs/index.mdx?collection=docs&hash=1751702889991"
import * as docs_1 from "../content/docs/design-principle.mdx?collection=docs&hash=1751702889991"
import * as docs_0 from "../content/docs/cli.mdx?collection=docs&hash=1751702889991"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"cli.mdx","absolutePath":"/home/hareesh/building/harukit-ui/apps/docs/content/docs/cli.mdx"}, data: docs_0 }, { info: {"path":"design-principle.mdx","absolutePath":"/home/hareesh/building/harukit-ui/apps/docs/content/docs/design-principle.mdx"}, data: docs_1 }, { info: {"path":"index.mdx","absolutePath":"/home/hareesh/building/harukit-ui/apps/docs/content/docs/index.mdx"}, data: docs_2 }, { info: {"path":"installation.mdx","absolutePath":"/home/hareesh/building/harukit-ui/apps/docs/content/docs/installation.mdx"}, data: docs_3 }, { info: {"path":"components/accordion.mdx","absolutePath":"/home/hareesh/building/harukit-ui/apps/docs/content/docs/components/accordion.mdx"}, data: docs_4 }, { info: {"path":"components/button.mdx","absolutePath":"/home/hareesh/building/harukit-ui/apps/docs/content/docs/components/button.mdx"}, data: docs_5 }, { info: {"path":"components/card.mdx","absolutePath":"/home/hareesh/building/harukit-ui/apps/docs/content/docs/components/card.mdx"}, data: docs_6 }, { info: {"path":"components/input.mdx","absolutePath":"/home/hareesh/building/harukit-ui/apps/docs/content/docs/components/input.mdx"}, data: docs_7 }, { info: {"path":"components/label.mdx","absolutePath":"/home/hareesh/building/harukit-ui/apps/docs/content/docs/components/label.mdx"}, data: docs_8 }, { info: {"path":"components/tooltip.mdx","absolutePath":"/home/hareesh/building/harukit-ui/apps/docs/content/docs/components/tooltip.mdx"}, data: docs_9 }], [])